### PR TITLE
Import Function

### PR DESCRIPTION
**Pull request by juliankoehn**
1. Added Import Function for csv files

> "username, password"
> "username2, password"
> "username3, password"

### CODE REVIEW

**Comment by chancity** [comment]
This isn't generic enough.   I started coding this but didn't finish.  Would you like to finish it?  It's the same concept but more generic.

**Comment by chancity** [comment]
I just pushed it.  Take a look.

**Comment by juliankoehn** [comment]
just made it as a quick "import" tonight 

your way is a lot clearer and tbh VB aint my language ;p

**Comment by juliankoehn** [comment]
i can change it to c# after this weekend if you like and add a few more repos

**Comment by chancity** [comment]
I pushed my version of batch import, feel free to add on or clean it up.

**Pull request closed without merging**
